### PR TITLE
Address Eric's AD review

### PR DESCRIPTION
**Pull request by tfpauly**

### CODE REVIEW

**Comment by evyncke** [comment]
Thank you Tommy, I still wonder about the use of "public address".

Is it defined as opposed of RFC 1918 private address ?

How would ULA and IPv[46] qualify as they are not RFC 1918 ?

-éric

**Review by tojens-ietf — APPROVED** [review]
LGTM

**Comment by evyncke** [comment]
[Interesting that my email reply did not make it]

Tommy, I saw this text about “public *host*” but the DDR text is about “public *address*”
 
I know that I am close to split hair... but let’s rather be explicit is a PS doc ;-)
 
-éric

**Comment by tfpauly** [comment]
Thanks @evyncke for the clarification! I switched the text from "non-public addresses" to "private addresses", since private addresses _are_ explicitly defined in 1918. (It does actually mention public addresses, too, but less often)

**Comment by evyncke** [comment]
Thanks for the change, but what about ULA & LLA ?

**Comment by evyncke** [comment]
Tommy, I saw this text about “public *host*” but the DDR text is about “public *address*”

I know that I am close to split hair... but let’s rather be explicit is a PS doc ;-)

-éric


From: Tommy Pauly ***@***.***>
Reply to: ietf-wg-add/draft-ietf-add-ddr ***@***.***>
Date: Thursday, 23 June 2022 at 18:17
To: ietf-wg-add/draft-ietf-add-ddr ***@***.***>
Cc: Eric Vyncke ***@***.***>, Comment ***@***.***>
Subject: Re: [ietf-wg-add/draft-ietf-add-ddr] Address Eric's AD review (PR #63)


RFC 1918 does define "public"

      Category 3: hosts that need network layer access outside the

                  enterprise (provided via IP connectivity); hosts in

                  the last category require IP addresses that are

                  globally unambiguous.



   We will refer to the hosts in the first and second categories as

   "private".  We will refer to the hosts in the third category as

   "public".

Should we clarify further? Do you have suggested text?

**Pull request merged**
