### PR TITLE
Add security consideration about dohpath attacks

### LINKED ISSUE #47: Forbid differential behavior based on DoH query path
As mentioned at the microphone, if we are to allow the query-path to be specified in the clear like this, we need to require that servers not have different responses with different query paths.

### PR DESCRIPTION
**Pull request by tfpauly**
Closes #47

### CODE REVIEW

**Comment by tfpauly** [comment]
@ekr, does this work for you?

**Review by ekr — APPROVED** [review]
LGTM

**Comment by ekr** [comment]
OK, so I said LGTM, but how does a server know that it is such a server? Can't I just publish a random DDR record for 1.1.1.1?

**Comment by bemasc** [comment]
As I mentioned in the session, this is partly covered in SVCB-DNS, but perhaps we need a tighter rule.  I've opened an issue to discuss it: https://github.com/ietf-wg-add/draft-ietf-add-svcb-dns/issues/9.

I'm not entirely sure which draft this kind of text ought to go in.  If you think this logic applies beyond DDR (e.g. in ADoT cases), then it probably should go in the SVCB-DNS draft.  Otherwise, maybe DDR is the place.

**Comment by tfpauly** [comment]
@bemasc for security considerations, I'm OK with multiple drafts having warnings. I think this particular attack should be mentioned in DDR, since other uses of DNS SVCB could be over more trusted channels.

**Comment by tfpauly** [comment]
@ekr if your resolver responds to _dns.resolver.arpa, then we expect the address of the resolver I asked to be covered in the cert. So, if I send a packet to 1.1.1.1, 1.1.1.1 has to be covered. 

So, if you just provide a "random" DDR record in response to _dns.resolver.arpa, you can only point to some resolver that has your IP address in its cert, which presumably is sufficient coordination for the resolver to "know" it has this set up.

**Comment by ekr** [comment]
Right. Good point.

**Pull request merged**
